\LoadClass[11pt]{report}

\usepackage[dutch]{babel}
\usepackage{graphicx}
\usepackage{titlesec}
\usepackage{wrapfig}
\usepackage{hyperref}
\usepackage{subfiles}
\usepackage[titletoc]{appendix}
\usepackage[a4paper]{geometry}
\usepackage[singlelinecheck=false]{caption}
\usepackage{array}
\usepackage{tocloft}
\usepackage{pdfpages}
\usepackage{pgfgantt}
\usepackage[utf8]{inputenc}

\titleformat{\chapter}
  {\Large\bfseries} % format
  {}                % label
  {0pt}             % sep
  {\huge}           % before-code
 